#Property file is nothing but it's a key value pare, that you don't want to hardcode.
# FRAMEWORK#
#===================

#Browsers : chrome, firefox, edge
browser=chrome

#Execution mode : local, remote etc.
execution_mode=local

#Headles mode: true, false (for CI/CD pipelines)
headless=false

#Remote WebDriver URL (Selenoid/Selenium Grid)
remote_url=https;//localhost:4444/wd/hub

# Selenoid Options
selenoid_video=true
selenoid_vnc=true

#### Project No 1 : App.vwo.com
url=https://app.vwo.com
url_dashboard=https://app.vwo.com/#/dashboard?accountId=1207845
url_free_trial=https://app.vwo.com/free-trial/
username=xgd39@burneremail.cc
password =Test@4321
